name: LinkedIn Scrape and Post

on:
  workflow_dispatch:   # permite lanzarlo manualmente
  schedule:
    - cron: '0 8 * * *'   # cada día a las 08:00 UTC

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Run scraper
        env:
          LI_AT: ${{AQEDAU0MVQwCJ7TwAAABmZYpWtQAAAGZujXe1FYAfn_EeZ9YPvnZKxQh7dk1lgL3ycC3ss54wyX9Fg6pai9kkMzVlMzUfTM0cnY5iBIU0vVHADwMiMPQbj3lwPL2h90Pm0bUTooE16yqhjusz2fSQuRr}}
          MAKE_WEBHOOK: ${{https://hook.eu2.make.com/6lotf12qjo3x63judau16ufhm8qvwjjd
}}
          LD_PROFILE_URL: ${{https://www.linkedin.com/in/vidalmarc/}}
          MAX_POSTS: ${{60}}
        run: |
          python scrape_and_post.py
